[build]
builder = "NIXPACKS"
aptPkgs = ["git-lfs"]
buildCommand = "git lfs install && git lfs pull && npm ci"

[deploy]
startCommand = "node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
